### PR TITLE
feat: ✨ Multi-language support

### PR DESCRIPTION
**Pull request by robvanderleek**

### CODE REVIEW

**Comment by chenrui333** [comment]
@robvanderleek since there is a license change with this PR, maybe it should be moved to a separate PR or cut a new release for it? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/168759

**Comment by robvanderleek** [comment]
Hi @chenrui333 

Yes, I was planning to make a new release for the license change.
I worked a lot on the code-analysis part the past weeks and decided the implementation deserves a more strict open-source license than ISC.

I wasn't aware my changes in `main` would trigger Homebrew builds (BTW I'm impressed by the active and kind support from Homebrew maintainers).

Is it enough if I make a new release? Also, if I'm missing some kind of best practice where my development activities in `main` should not immediately lead to Homebrew changes, let me know.

**Comment by robvanderleek** [comment]
Hi @chenrui333
FYI I've released version 0.9.0: https://pypi.org/project/codelimit/0.9.0/

**Comment by chenrui333** [comment]
yeah, new release would be good, but I notice there is some license discrepancy issue in the README though. Besides GPL-3.0 is deprecated. I will drop a quick PR on this. Thanks!

**Pull request merged**
